apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:ALxiSMUzXJrOtEeBamycBE0ecYOR7/hlCQZMRoXnmw05YhwNg8spFg==,iv:Cm5DgeoKC2tjZDW09zBj7RAZV7w4SW9HWWW8pdB9h+4=,tag:2ZUrSNmE3+3gEPg65L8tvQ==,type:str]
    admin-user: ENC[AES256_GCM,data:X/OzLyw=,iv:Yyx/L9nzkBYYgJ8owKXg6OIf+QNiygDJIzuw5gxHXVw=,tag:13RRM1svBxYyx965Wt6DYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10frej8uzvutnfv7j8s29tu488tfa69aqc4wwdhej7tmh4uynqf2qpum577
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMmFCYnJqdmYxSE1VUlF1
            dWp3WVdCS0l5S2xvcWUzN3dON0pPa3p2ajNRClBnMDBmS2xpQlg4QTB4c0FNNVN2
            aHR6UkxyY0kySWxjZ0wwTHJsWDdtQkEKLS0tIFl2ZE9yOHlOZURpOHFrSS9tTkFJ
            YnUyUVZOdTJRV1ZUTnAxOW1DMFd3ZnMK6pdo1Qjz/TLTpXzFfudi3pB4Dd0pUY94
            FFFMw9NckkOqPf/eVY7sq+yRHkGjr+Q+2gEjo/NiCDsnqXFke3N0kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T05:03:39Z"
    mac: ENC[AES256_GCM,data:9h4n89qDK4RsP8+I0V3Rjy6LU8nd90j7pd1rMmj2/GTpQ+K+bGlOAHaU0O1+tN3yy8DAJb4E2fVDJ8XwiMdmXZOhF3w/NlF5WrdxSxeEjZ+1hY2XsvWaFQU2pf7g31TSd1ngy7+K54fT4kXBV9p9xQRvg1YnaPmOrLZdvT8YZyc=,iv:ov4z8ZHFTLvNwySmhgkVpK2Xnncsf7zKO+uH8ZG1oZE=,tag:fbgRjj/obaK3n515TqecQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
