---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
    - ./authentik-pvc.yaml
    - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/part-of: longhorn
