apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pyq2c5pqhn9627hY,iv:MkLVXdTcvdnn+x3l41CieHGL7zAI80jIvLH9bC/CyRU=,tag:3X8wHFObqunkyvq+19K6JA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ntK83GQ4Qdu67UtdCH8HWfbo7tlEjISNldULs/J39ZLqGZDa,iv:M1RwINy2UyEHzY5B1RZ4HQQiMq4F05JljnGfW/KGap0=,tag:wX+kfePgeMxpMlWCxa6Vqg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vSb3RZyJoyIT/+0=,iv:jCSCe2SyDmGNacBLFxkeiY+7uYu2QTFWf3RJb9ESoR4=,tag:uRHYoobTgzslgTbUywZDmA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XAtEJAcXprO736A1,iv:PdeP7iaahDebLrhCVqucODI+uG6Z2boTe7qvtr53VLc=,tag:Xmgvj5xQdYttSp35K6VymA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:T6v3iGNAHBYUlOxr7cJYqKzqkgc=,iv:vGwuHN3s/LjBHfNZCUpwSFkHEupKlK25/vHRnDSRNPA=,tag:JsX+6X/5qmlFb78vM0LIbg==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:7xlNqPrYFS2ecq2KDUcGfZHy5In7im91C4uMEs1wNigk4j7rRUgIAYpuMdae3IoJICo=,iv:1qzH+LKwWovmExqp0j5bWbfdo73h/4phFOnRo3e7nRs=,tag:fLMtLP2LhQo9WXETW2plFw==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:xUSwHyWwDjY7JmX5MsEvhKHtps5nnfW7yR7McDxkRmpHWPVOCMiuiA==,iv:SeMOFUDQBXLtIqWB+oEKN5IqXgu7l/+xbUf8D3E4mgQ=,tag:qxsBkpwmaDoGh8WpzsSv0g==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:K7XNIM7E+CriR3oqAd7uMv26ep8Yhxi9OrpBZwG6xhCIwgqeNPeZ7w==,iv:AmOgNuLTrP3BFmeWiAIb/fNCuoL9hdqAly3jnoF5/ms=,tag:dZ0St24rUGdjeHbEEWXy3A==,type:str]
    NAS_IP: ENC[AES256_GCM,data:4mPCUn6FXS2X,iv:Qi4R91XtmhPaCBQiE5swBdx4Dg8u2sHwyiRuDvhrL+g=,tag:762aohd9dB5VcZXGlgZbdw==,type:str]
    PROXMOX_IP: ENC[AES256_GCM,data:1qcODqoFZ4zo,iv:VuwsYolZoHVgp+hpcWp9TfUc7PWyJq7eAXqryg4PVs0=,tag:f1ux8RY8vIw5ZPfOXWDCTA==,type:str]
    OPNSENSE_IP: ENC[AES256_GCM,data:3fXhSGR+DYlY,iv:/GbNw5jvYPq0dOCzGParqlExOL1SGS+Ku1kck3btqGQ=,tag:dMSdbPsZgyw5V1WwLh3jNQ==,type:str]
    AD_IP: ENC[AES256_GCM,data:8YyBdGFyzpiLGRQ=,iv:avoJ97OuVna+gBFUkrWFQ67LABLjAIHJ4AACdu3r0ro=,tag:3yIuhM3Mw0RmUPjSatN1qg==,type:str]
    SECRET_NFS_BACKUP: ENC[AES256_GCM,data:NsMDKU3FSApK,iv:wEfR1DMCQ/vg0sHXq0YZnWxtLllad6wfIy0AOAH/J9Q=,tag:BZohyY7yKeCDq0lRx/G6kw==,type:str]
    AUTHENTIK_KEY: ENC[AES256_GCM,data:D++D6VhK/l6Zg2vMpK/wNgSE+Jo8/V17dglm8XS+vOs7gAou8s9hN4rvtXlYPHamrEo=,iv:ucsXiK9bHElI7BYkvjyLvKQl7guKUBSalnOB/xcJ/n4=,tag:lwujHYmRwJkj8jrTTUulnA==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:Vle+PqWSB4OEu+2Yydg4Mz5cB4TS64KXXJEpm2wVUqcibPJAw2XzOPmtyShmyqvriGw=,iv:7me0UHoN+GfjOT8Ibb2mnq0MDFmRapebaQ4oAA8YUFw=,tag:TsTuenE2v15gtVIAnAmknQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:N3aBh1lZVxlxkavGWHmz,iv:2twF1hbJh7yKDpxHVTwfHM+012NwbKKwcmXQ6ZmtKtg=,tag:eZBb8cYeHpWIfUGS2KJR2g==,type:str]
    LATITUDE: ENC[AES256_GCM,data:L0pelMbWlPc=,iv:znaLUgVOwKrrflOK44wOfpPJo8i8x3IjM9pFsILp1LM=,tag:zt7uLHZlSuulQKrxaRMCOw==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:kSmvt1rzw3gq,iv:RXyjJn5EXGgJlnc3PVXnYpcyirSVZiBT/9vU2z8rwe8=,tag:kd0ulGxMfe8cjf8XTkNoSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10frej8uzvutnfv7j8s29tu488tfa69aqc4wwdhej7tmh4uynqf2qpum577
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUUpQY2twdlVyK1J3eHRX
            UlJiZlhlRnJER1dKMmJGY3ZrWWtkNG1veUFJCnQ2NXgzWVFMbW5WUW1uUngrWm5t
            M1pIeTQwbzM0T1VYZVpkV1lCZnc5REkKLS0tIDdYd3Y1SEJlNzQvdVVLVWRDRTNT
            Qi9sbnpUN29yMjRqRTc0UlBXcC91RmcKokkMHc0IvT9rhzHg/n2n2ENc/3XGRyms
            lQ6uOnR+K/R7mH2RWrRGzqIh2jsceLsdcUBZEl1GHTTKPf5/uQi7Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-11T02:48:23Z"
    mac: ENC[AES256_GCM,data:I2Tq0FwKWPTBFii6xP/Hrv1F7qRtiexNdA4YZAzMFqH+IR532UoDvYW8q4w47DvpEzSN1SPAuqmx9oMvcItZDi4j6a8U7UMtusYepMULTpUXoBMpq0du78XQLxPN8SX/t7LOVYoiDGW5SCNlML967ro8At9U/vUGHb3XNVAre5Y=,iv:6ZxnWsGuP5/4CYyVLB5ssVjfKxd8NH7BW94McZFwmQ8=,tag:6NGL7zaG+EeLDrvBKu9lhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
