apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:davUpmQjo11qaPEWCYg80zIjxCgDohu4tSJQuq6arZyUJgcl,iv:WTbEfIZoqqNqLfEF9/0rPI17T3bnfqc90BTBeWyV+88=,tag:CZ3XMUfK5z2n7AfillwmXA==,type:str]
    credentials.json: ENC[AES256_GCM,data:w5j4Cd1eGP/9IGhctKnjnNllyo5u9IDzONu4qQiUpmsRlFqeJOPow+32Y89JOh9SKd2rXN5AIWL+5swR6JBJjf1XIOFPVWTgbqV9tPqx2fYIx74dy+zuM/5qg3jiBROduTrRZxO9JPma/VB1Dm9C9obSr7Uc5rhlPpEG1+yo8nwXI0WaHYOcJc8VO2wufCB0pYJfdnXmM6ucdVsBIn2gk6U5xuurWn7GOK+LmWv5gg==,iv:YTBdLIa6TLFM8XPPutZMQs5HZ/nOKtRrmtt4T1wY978=,tag:XZxRFniGBVMcVCbD7G5V3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10frej8uzvutnfv7j8s29tu488tfa69aqc4wwdhej7tmh4uynqf2qpum577
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbjMwaHVVOVRTTmFTTmU3
            cGxwTFg4aGNPZHJIWjBPYVJlSklVcG8rM2lRCnE2L1J2alFkRi9LVlpUa3dOUG11
            RmhYc3Q4dXUzRWZMaUp0VWdLUmFCWnMKLS0tIElhQWdLVk4xRnJQS3oxcWpkbjBZ
            TVZUUW1kMXBNN1FNckQyaEtHajNSbGcKWHJCJmchS5M1Vxv1ynCmN1r4omuWpkBB
            j6oXoKyScoFXL3DYiSbS5gfamIrPfIpL9NeWE6rmDqrlzTe/EsZ8aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-10T05:03:33Z"
    mac: ENC[AES256_GCM,data:/+/edpmcfYfJj9FwLsslnHJ1GVuIg0Vy30sKJD396nNC7r0vTULcjXaAzY5WmG5DGHuqzcwkCCqZyPf2arDaKb1oJABmGOR7wGPoFoi5WlO+NxL8s4rZ2ECluBr+kTCYxLIdFWESjCIRFnCpgbEPp8InoJUEXx99aqErPkEBD90=,iv:Oom/VbUyuv5pR8EsT7bZ4J3wgtEEA/9tJ4CboiwXKHM=,tag:dex6OQJX5BfJDA21tcmJXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
